sudo: required
dist: trusty
language: go
go:
  - 1.5

env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit-go"
    - TEST_SUITE="--unit-js"

cache:
  directories:
    - node_modules

install:
  - if [ "$TEST_SUITE" == "--unit-js" ]; then . $HOME/.nvm/nvm.sh && nvm install stable && nvm use stable; fi
script: sh -v ./run-checks $TEST_SUITE
